<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>NVIDIA ShadowPlay.ico</ApplicationIcon>
    <AssemblyTitle>NVIDIA ShadowPlay Helper Services</AssemblyTitle>
    <Product>NVIDIA ShadowPlay</Product>
    <Company>NVIDIA Corporation</Company>
    <Version>3.28.0.412</Version>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <AssemblyName>nvsphelper</AssemblyName>
    <RootNamespace>NvShadowPlayHelper</RootNamespace>
    <OutputPath>C:\My Project\NVIDIA-Shadowplay\build\NVIDIA ShadowPlay\NvContainer\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <!-- NVIDIA ShadowPlay Helper — ดัก Alt+Z ยิงให้ NvContainer (hotkey-only) -->
  </PropertyGroup>

</Project>
