<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<RootNamespace>NVIDIA_Experience</RootNamespace>
		<UseWindowsForms>true</UseWindowsForms>
		<MyType>WindowsForms</MyType>
		<TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
		<SupportedOSPlatformVersion>10.0.26100.0</SupportedOSPlatformVersion>
		<StartupObject>NVIDIA_Experience.My.MyApplication</StartupObject>
		<ApplicationIcon>NVIDIA ShadowPlay.ico</ApplicationIcon>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

	<ItemGroup>
	  <Content Include="NVIDIA ShadowPlay.ico" />
	</ItemGroup>

	<ItemGroup>
		<Import Include="System" />
		<Import Include="System.Collections" />
		<Import Include="System.Collections.Generic" />
		<Import Include="System.Data" />
		<Import Include="System.Diagnostics" />
		<Import Include="System.Drawing" />
		<Import Include="System.Linq" />
		<Import Include="System.Threading.Tasks" />
		<Import Include="System.Windows.Forms" />
		<Import Include="Microsoft.VisualBasic" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="[Forms - Project Files]\[API]\TCP\[APP] Client.vb" />
	</ItemGroup>

</Project>