<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Project\ShadowPlay\NvCapture\CaptureEngine.dll\CaptureEngine.vbproj" />
    <ProjectReference Include="..\..\..\Project\ShadowPlay\NvCapture\CaptureEngine.Video.dll\CaptureEngine.Video.vbproj" />
    <ProjectReference Include="..\..\..\Project\ShadowPlay\NvCapture\CaptureEngine.Video.Ddagrab.dll\CaptureEngine.Video.Ddagrab.vbproj" />
    <ProjectReference Include="..\..\..\Project\ShadowPlay\NvCapture\CaptureEngine.Encoder.dll\CaptureEngine.Encoder.vbproj" />
    <ProjectReference Include="..\..\..\Project\ShadowPlay\NvCapture\CaptureEngine.Encoder.Nvenc.dll\CaptureEngine.Encoder.Nvenc.vbproj" />
  </ItemGroup>
</Project>
