/* GENERATED by Build/Build-Config/bl1-cpp.targets - do not edit. */
#undef SHARE_FILEVERSION
#undef SHARE_FILEVERSION_STR
#define SHARE_FILEVERSION 3,41,3872,61
#define SHARE_FILEVERSION_STR "3.41.3872.61\0"
